import './globals.css'
import { Inter } from 'next/font/google'
import SideBar from "@/components/SideBar";
import Navbar from "@/components/Navbar"
// import { Html, Head, Main, NextScript } from 'next/document';
import Head from 'next/head';
import { Title } from 'chart.js';
import { Metadata } from 'next';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons:{
    icons:[
      '../public/favicon.ico'
    ]
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <title>GYM</title>
      </Head>
      <body className={inter.className}>{children}
      </body>

    </html>
    
  )
}
